esphome:
  name: ac-remote

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "1KMEt//8JQxaEtboIP50bbRrwcPWuKW7ux6aJUfaclE="

ota:
  password: "08fe0b48811d372c75716ce35e1f8bf8"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ac-Remote Fallback Hotspot"
    password: "fADey9cQ9KfM"

captive_portal:

esp32_ble_tracker: # sets up the ble stack on the device and listens for available devices

binary_sensor:
  # Presence based on BLE Service UUID
  - platform: ble_presence
    service_uuid: '11aa'
    name: "ESP32 BLE Tracker Test Service 16 bit"
  # Presence based on iBeacon UUID
  - platform: ble_presence
    ibeacon_uuid: '68586f1e-89c2-11eb-8dcd-0242ac130003'
    name: "ESP32 BLE Tracker Test Service iBeacon"

# receive incoming IR signals and dump them to log file
remote_receiver:
  pin: 
    number: GPIO15
    inverted: true
  dump: all

# our IR transmitter
remote_transmitter:
  pin:
    number: GPIO32
  carrier_duty_percent: 50%

button:
  - platform: template
    name: "Power On Button"
    id: on_button
    on_press:
      - logger.log: "AC turned on :)"
      - remote_transmitter.transmit_pronto:
          data: "0000 006D 0022 0000 0161 00AD 0017 0015 0017 0016 0016 0015 0017 0015 0017 0015 0017 0015 0017 0015 0017 0015 0017 003F 0017 003F 0017 003F 0017 003F 0017 0015 0017 0040 0016 003F 0017 003F 0017 003F 0017 003F 0017 0015 0017 0015 0017 0015 0017 0015 0017 0015 0017 0015 0017 0015 0017 0015 0017 003F 0017 003F 0017 003F 0017 003F 0017 003F 0017 003F 0017 06C3"
      - remote_transmitter.transmit_lg:
          data: 0x00F7C03F # power on/off
          nbits: 32
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xFC03
  
  - platform: template
    name: "Power Off Button"
    id: off_button
    on_press:
      - logger.log: "AC turned off :)"
      - remote_transmitter.transmit_pronto:
          data: "0000 006D 0022 0000 0164 00AD 0017 0015 0017 0015 0017 0015 0017 0015 0017 0015 0017 0015 0017 0015 0017 0015 0017 003F 0017 003F 0017 003F 0017 003F 0017 0015 0017 003F 0018 003F 0017 003F 0017 0015 0017 003F 0017 0015 0017 0015 0017 0015 0017 0015 0017 0015 0017 0015 0017 003F 0017 0015 0017 003F 0017 003F 0017 003F 0017 003F 0017 003F 0017 003F 0017 06C3"
      - remote_transmitter.transmit_lg:
          data: 0x00F740BF # power on/off
          nbits: 32
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xFD02
          
