esphome:
  name: max

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Cof239sBos61xRT3hMohKMjA9MK5WFR+ntdclNmV0T4="

ota:
  password: "e049ac7af50c8921c8e8964d6096cc34"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Max Fallback Hotspot"
    password: "WD5YjDKxCGzj"

captive_portal:

remote_receiver: # receive incoming IR signals and dump them to log file
  pin: 
    number: GPIO15
    inverted: true
  dump: all
  
remote_transmitter:
  pin:
    number: GPIO32
  carrier_duty_percent: 50%

button:
  - platform: template
    name: "Power Button"
    id: on_button
    on_press:
      - logger.log: "AC turned on :)"
      - remote_transmitter.transmit_pronto:
          data: "0000 006D 0022 0000 0159 00AB 0016 0014 0017 0015 0018 0012 0016 0014 0017 0014 0019 0013 001A 0010 0016 0014 0019 003E 0016 003F 0016 0040 001D 0038 001C 003C 0015 003F 0019 003D 0017 003F 0016 0015 001B 000F 0019 0012 0016 0014 0017 0014 0019 0012 0016 0040 0018 0013 0015 003F 0019 003D 0017 003F 0016 003F 0017 003F 0016 0040 0015 0014 0017 0040 0015 06C3"
          
